export const PRODUCT_INFO_TYPES = {
  electronics: {
    name: '전자제품',
    fields: [
      { key: 'manufacturer', label: '제조업체/수입업체', type: 'text', required: true },
      { key: 'origin', label: '제조국/원산지', type: 'text', required: true },
      { key: 'modelName', label: '모델명', type: 'text', required: false },
      { key: 'manufacturingDate', label: '제조연월', type: 'month', required: false },
      { key: 'kc', label: 'KC 인증정보', type: 'text', required: false },
      { key: 'qualityAssurance', label: '품질보증기준', type: 'text', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', type: 'text', required: true },
      { key: 'powerConsumption', label: '소비전력', type: 'text', required: false },
      { key: 'energyEfficiency', label: '에너지효율등급', type: 'text', required: false },
    ],
  },
  clothing: {
    name: '의류',
    fields: [
      { key: 'manufacturer', label: '제조업체/수입업체', type: 'text', required: true },
      { key: 'origin', label: '제조국/원산지', type: 'text', required: true },
      { key: 'material', label: '소재', type: 'text', required: true },
      { key: 'color', label: '색상', type: 'text', required: false },
      { key: 'size', label: '치수', type: 'text', required: false },
      { key: 'manufacturingDate', label: '제조연월', type: 'month', required: false },
      { key: 'washingMethod', label: '세탁방법 및 취급시 주의사항', type: 'textarea', required: true },
      { key: 'qualityAssurance', label: '품질보증기준', type: 'text', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', type: 'text', required: true },
    ],
  },
  food: {
    name: '식품',
    fields: [
      { key: 'manufacturer', label: '제조업체/수입업체', type: 'text', required: true },
      { key: 'origin', label: '원산지', type: 'text', required: true },
      { key: 'expirationDate', label: '유통기한', type: 'date', required: true },
      { key: 'storageMethod', label: '보관방법', type: 'text', required: true },
      { key: 'capacity', label: '용량/중량', type: 'text', required: true },
      { key: 'nutrition', label: '영양성분', type: 'textarea', required: false },
      { key: 'allergyInfo', label: '알레르기 정보', type: 'textarea', required: false },
      {
        key: 'geneticModification',
        label: '유전자변형식품 여부',
        type: 'select',
        options: ['해당없음', '유전자변형식품', '유전자변형식품 포함'],
        required: false,
      },
    ],
  },
  cosmetics: {
    name: '화장품',
    fields: [
      { key: 'manufacturer', label: '제조업체/수입업체', type: 'text', required: true },
      { key: 'origin', label: '제조국/원산지', type: 'text', required: true },
      { key: 'expirationDate', label: '사용기한', type: 'date', required: true },
      { key: 'capacity', label: '용량/중량', type: 'text', required: true },
      { key: 'ingredients', label: '주요 성분', type: 'textarea', required: false },
      { key: 'usage', label: '사용법', type: 'textarea', required: false },
      { key: 'precautions', label: '사용시 주의사항', type: 'textarea', required: true },
      {
        key: 'functionalCosmetic',
        label: '기능성화장품 여부',
        type: 'select',
        options: ['해당없음', '기능성화장품'],
        required: false,
      },
    ],
  },
  books: {
    name: '도서',
    fields: [
      { key: 'publisher', label: '출판사', type: 'text', required: true },
      { key: 'author', label: '저자', type: 'text', required: true },
      { key: 'publishDate', label: '출간일', type: 'date', required: true },
      { key: 'isbn', label: 'ISBN', type: 'text', required: false },
      { key: 'pages', label: '쪽수', type: 'number', required: false },
      { key: 'size', label: '크기', type: 'text', required: false },
      { key: 'weight', label: '무게', type: 'text', required: false },
      { key: 'language', label: '언어', type: 'text', required: false },
    ],
  },
  furniture: {
    name: '가구',
    fields: [
      { key: 'manufacturer', label: '제조업체/수입업체', type: 'text', required: true },
      { key: 'origin', label: '제조국/원산지', type: 'text', required: true },
      { key: 'material', label: '주요 소재', type: 'text', required: true },
      { key: 'size', label: '크기', type: 'text', required: true },
      { key: 'weight', label: '무게', type: 'text', required: false },
      { key: 'color', label: '색상', type: 'text', required: false },
      { key: 'manufacturingDate', label: '제조연월', type: 'month', required: false },
      { key: 'qualityAssurance', label: '품질보증기준', type: 'text', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', type: 'text', required: true },
      { key: 'assemblyRequired', label: '조립여부', type: 'select', options: ['완제품', '조립필요'], required: false },
    ],
  },
  sports: {
    name: '스포츠용품',
    fields: [
      { key: 'manufacturer', label: '제조업체/수입업체', type: 'text', required: true },
      { key: 'origin', label: '제조국/원산지', type: 'text', required: true },
      { key: 'material', label: '소재', type: 'text', required: true },
      { key: 'size', label: '크기', type: 'text', required: false },
      { key: 'weight', label: '무게', type: 'text', required: false },
      { key: 'manufacturingDate', label: '제조연월', type: 'month', required: false },
      { key: 'qualityAssurance', label: '품질보증기준', type: 'text', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', type: 'text', required: true },
      { key: 'safetyStandard', label: '안전기준', type: 'text', required: false },
    ],
  },
  general: {
    name: '일반상품',
    fields: [
      { key: 'manufacturer', label: '제조업체/수입업체', type: 'text', required: true },
      { key: 'origin', label: '제조국/원산지', type: 'text', required: true },
      { key: 'manufacturingDate', label: '제조연월', type: 'month', required: false },
      { key: 'qualityAssurance', label: '품질보증기준', type: 'text', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', type: 'text', required: true },
      { key: 'additionalInfo', label: '기타 정보', type: 'textarea', required: false },
    ],
  },
};
