import { ProductInfomationDisclosureType } from '@/features/products/types/product.types';

export const PRODUCT_INFO_DISC_CATEGORY = {
  clothing: {
    id: 'PID-01',
    name: '의류',
  },
  footwear: {
    id: 'PID-02',
    name: '구두 / 신발',
  },
  bag: {
    id: 'PID-03',
    name: '가방',
  },
  fashionAccessories: {
    id: 'PID-04',
    name: '패션잡화 (모자 / 벨트 / 액세서리 등)',
  },
  bedding: {
    id: 'PID-05',
    name: '침구류 / 커튼',
  },
  furniture: {
    id: 'PID-06',
    name: '가구 (침대 / 소파 / 싱크대 / DIY제품 등)',
  },
  electronics: {
    id: 'PID-07',
    name: '영상가전 (TV류)',
  },
  homeAppliances: {
    id: 'PID-08',
    name: '가정용 전기제품 (냉장고 / 세탁기 / 식기세척기 / 전자레인지 등)',
  },
  seasonalAppliances: {
    id: 'PID-09',
    name: '계절가전 (에어컨 / 온풍기 등)',
  },
  officeEquipment: {
    id: 'PID-10',
    name: '사무용기기 (컴퓨터 / 노트북 / 프린터 등)',
  },
  opticalEquipment: {
    id: 'PID-11',
    name: '광학기기 (디지털카메라 / 캠코더 등)',
  },
  smallElectronic: {
    id: 'PID-12',
    name: '소형전자 (MP3 / 전자사전 등)',
  },
  mobileCommunication: {
    id: 'PID-13',
    name: '휴대형 통신기기 (휴대폰 / 태블릿 등)',
  },
  navigation: {
    id: 'PID-14',
    name: '내비게이션',
  },
  automotive: {
    id: 'PID-15',
    name: '자동차용품 (자동차부품 / 기타 자동차용품 등)',
  },
  medicalEquipment: {
    id: 'PID-16',
    name: '의료기기',
  },
  kitchen: {
    id: 'PID-17',
    name: '주방용품',
  },
  cosmetics: {
    id: 'PID-18',
    name: '화장품',
  },
  jewelry: {
    id: 'PID-19',
    name: '귀금속 / 보석 / 시계류',
  },
  agricultural: {
    id: 'PID-20',
    name: '농수축산물',
  },
  processedFood: {
    id: 'PID-21',
    name: '가공식품',
  },
  healthFood: {
    id: 'PID-22',
    name: '건강기능식품',
  },
  children: {
    id: 'PID-23',
    name: '어린이제품',
  },
  musicalInstrument: {
    id: 'PID-24',
    name: '악기',
  },
  sports: {
    id: 'PID-25',
    name: '스포츠용품',
  },
  books: {
    id: 'PID-26',
    name: '서적',
  },
  hotel: {
    id: 'PID-27',
    name: '호텔 / 펜션 예약',
  },
  travelPackage: {
    id: 'PID-28',
    name: '여행패키지',
  },
  airlineTicket: {
    id: 'PID-29',
    name: '항공권',
  },
  rentalCar: {
    id: 'PID-30',
    name: '자동차 대여 서비스 (렌터카)',
  },
  rentalProduct: {
    id: 'PID-31',
    name: '물품대여 서비스 (정수기, 비데, 공기청정기 등)',
  },
  rentalBook: {
    id: 'PID-32',
    name: '물품대여 서비스 (서적, 유아용품, 행사용품 등)',
  },
  digitalContent: {
    id: 'PID-33',
    name: '디지털 콘텐츠 (음원, 게임, 인터넷강의 등)',
  },
  giftCard: {
    id: 'PID-34',
    name: '상품권 / 쿠폰',
  },
  mobileCoupon: {
    id: 'PID-35',
    name: '모바일 쿠폰',
  },
  moviePerformance: {
    id: 'PID-36',
    name: '영화·공연',
  },
  chemicalProduct: {
    id: 'PID-37',
    name: '생활화학제품',
  },
  biologicalProduct: {
    id: 'PID-38',
    name: '살생물제품',
  },
  service: {
    id: 'PID-39',
    name: '기타 용역',
  },
  others: {
    id: 'PID-40',
    name: '기타',
  },
} as const;

export const PRODUCT_INFO_DISC_TYPES: Record<string, ProductInfomationDisclosureType> = {
  clothing: {
    ...PRODUCT_INFO_DISC_CATEGORY['clothing'],
    fields: [
      {
        key: 'material',
        label: '제품 소재',
        placeholder: '(섬유의 조성 또는 혼용률을 백분율로 표시, 기능성인 경우 성적서 또는 허가서)',
        type: 'textarea',
        required: true,
      },
      { key: 'color', label: '색상', required: true },
      { key: 'size', label: '치수', required: true },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기 ',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'washingMethod', label: '세탁방법 및 취급시 주의사항', type: 'textarea', required: true },
      { key: 'qualityAssurance', label: '품질보증기준', required: true },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  footwear: {
    ...PRODUCT_INFO_DISC_CATEGORY['footwear'],
    fields: [
      {
        key: 'material',
        label: '제품 주소재',
        placeholder: '(운동화인 경우에는 겉감, 안감을 구분하여 표시)',
        type: 'textarea',
        required: true,
      },
      { key: 'color', label: '색상', required: false },
      {
        key: 'size',
        label: '치수',
        placeholder:
          '(발길이: 해외사이즈 표기시 국내사이즈 병행 표기(mm), 굽높이: 굽 재료를 사용하는 여성화에 한함(cm))',
        required: false,
      },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'washingMethod', label: '세탁방법 및 취급시 주의사항', type: 'textarea', required: true },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  bag: {
    ...PRODUCT_INFO_DISC_CATEGORY['bag'],
    fields: [
      { key: 'type', label: '종류', required: true },
      { key: 'material', label: '소재', type: 'textarea', required: true },
      { key: 'color', label: '색상', required: false },
      { key: 'size', label: '크기', required: false },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'washingMethod', label: '세탁방법 및 취급시 주의사항', type: 'textarea', required: true },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  fashionAccessories: {
    ...PRODUCT_INFO_DISC_CATEGORY['fashionAccessories'],
    fields: [
      { key: 'kind', label: '종류', required: true },
      { key: 'material', label: '소재', type: 'textarea', required: true },
      { key: 'size', label: '치수', required: false },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'washingMethod', label: '세탁방법 및 취급시 주의사항', type: 'textarea', required: true },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  bedding: {
    ...PRODUCT_INFO_DISC_CATEGORY['bedding'],
    fields: [
      {
        key: 'material',
        label: '제품 소재',
        placeholder: '(섬유의 조성 또는 혼용률을 백분율로 표시)',
        type: 'textarea',
        required: true,
      },
      { key: 'color', label: '색상', required: false },
      { key: 'size', label: '치수', required: false },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'washingMethod', label: '세탁방법 및 취급시 주의사항', type: 'textarea', required: true },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  furniture: {
    ...PRODUCT_INFO_DISC_CATEGORY['furniture'],
    fields: [
      { key: 'productName', label: '품명', required: true },
      { key: 'kc', label: 'KC 인증정보', type: 'textarea', required: false },
      { key: 'color', label: '색상', required: false },
      { key: 'components', label: '구성품', type: 'textarea', required: false },
      { key: 'material', label: '주요 소재', type: 'textarea', required: true },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'size', label: '크기', required: false },
      {
        key: 'refurbish',
        label: '재공급(리퍼브) 가구의 경우 재공급 사유 및 하자 부위에 관한 정보',
        placeholder: '(예시 : 견본주택 전시상품으로 식탁 상판에 미세한 흠집 있음 등)',
        type: 'textarea',
        required: false,
      },
      { key: 'deliveryCost', label: '배송 · 설치비용', required: false },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  electronics: {
    ...PRODUCT_INFO_DISC_CATEGORY['electronics'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: false },
      {
        key: 'kc',
        label: 'KC 인증정보',
        placeholder:
          '([전기용품 및 생활용품 안전관리법]에 따른 안전인증·안전확인·공급자적합성확인대상제품 및 [전파법]에 따른 적합인증·적합등록 대상 기자재에 한함)',
        type: 'textarea',
        required: false,
      },
      { key: 'powerConsumption', label: '정격전압, 소비전력', required: false },
      {
        key: 'energyEfficiency',
        label: '에너지소비효율등급',
        placeholder: '([에너지이용 합리화법]에 따른 에너지소비효율등급 표시대상 기자재에 한함)',
        required: false,
      },
      { key: 'manufacturingDate', label: '동일모델의 출시년월', required: false },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'size', label: '크기, 형태', required: false },
      { key: 'powerConsumption', label: '화면사양 (화면크기, 해상도, 화면비율 등)', type: 'textarea', required: false },
      { key: 'deliveryCost', label: '추가설치비용', required: false },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  homeAppliances: {
    ...PRODUCT_INFO_DISC_CATEGORY['homeAppliances'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: false },
      {
        key: 'kc',
        label: 'KC 인증정보',
        placeholder:
          '([전기용품 및 생활용품 안전관리법]에 따른 안전인증·안전확인·공급자적합성확인대상제품 및 [전파법]에 따른 적합인증·적합등록 대상 기자재에 한함)',
        type: 'textarea',
        required: false,
      },
      { key: 'powerConsumption', label: '정격전압, 소비전력', required: false },
      {
        key: 'energyEfficiency',
        label: '에너지소비효율등급',
        placeholder: '([에너지이용 합리화법]에 따른 에너지소비효율등급 표시대상 기자재에 한함)',
        required: false,
      },
      { key: 'manufacturingDate', label: '동일모델의 출시년월', required: false },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'size', label: '크기, 용량, 형태', type: 'textarea', required: false },
      { key: 'deliveryCost', label: '추가설치비용', required: false },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  seasonalAppliances: {
    ...PRODUCT_INFO_DISC_CATEGORY['seasonalAppliances'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: false },
      {
        key: 'kc',
        label: 'KC 인증정보',
        placeholder:
          '([전기용품 및 생활용품 안전관리법]에 따른 안전인증·안전확인·공급자적합성확인대상제품 및 [전파법]에 따른 적합인증·적합등록 대상 기자재에 한함)',
        type: 'textarea',
        required: false,
      },
      { key: 'powerConsumption', label: '정격전압, 소비전력', required: false },
      {
        key: 'energyEfficiency',
        label: '에너지소비효율등급',
        placeholder: '([에너지이용 합리화법]에 따른 에너지소비효율등급 표시대상 기자재에 한함)',
        required: false,
      },
      { key: 'manufacturingDate', label: '동일모델의 출시년월', required: false },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'size', label: '크기, 형태 (실외기 포함)', type: 'textarea', required: false },
      { key: 'powerConsumption', label: '냉난방면적', required: false },
      { key: 'deliveryCost', label: '추가설치비용', required: false },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  officeEquipment: {
    ...PRODUCT_INFO_DISC_CATEGORY['officeEquipment'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: false },
      {
        key: 'kc',
        label: 'KC 인증정보',
        placeholder:
          '([전기용품 및 생활용품 안전관리법]에 따른 안전인증·안전확인·공급자적합성확인대상제품 및 [전파법]에 따른 적합인증·적합등록 대상 기자재에 한함)',
        type: 'textarea',
        required: false,
      },
      { key: 'powerConsumption', label: '정격전압, 소비전력', required: false },
      {
        key: 'energyEfficiency',
        label: '에너지소비효율등급',
        placeholder: '([에너지이용 합리화법]에 따른 에너지소비효율등급 표시대상 기자재에 한함)',
        required: false,
      },
      { key: 'manufacturingDate', label: '동일모델의 출시년월', required: false },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'size', label: '크기, 무게', placeholder: '(무게는 노트북 등 휴대형 기기에 한함)', required: false },
      {
        key: 'powerConsumption',
        label: '주요 사양',
        placeholder: '(컴퓨터와 노트북의 경우 성능, 용량, 운영체제 포함여부 등 / 프린터의 경우 인쇄 속도 등)',
        type: 'textarea',
        required: false,
      },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  opticalEquipment: {
    ...PRODUCT_INFO_DISC_CATEGORY['opticalEquipment'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: false },
      {
        key: 'kc',
        label: 'KC 인증정보',
        placeholder:
          '([전기용품 및 생활용품 안전관리법]에 따른 안전인증·안전확인·공급자적합성확인대상제품 및 [전파법]에 따른 적합인증·적합등록 대상 기자재에 한함)',
        type: 'textarea',
        required: false,
      },
      { key: 'manufacturingDate', label: '동일모델의 출시년월', required: false },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'size', label: '크기, 무게', required: false },
      {
        key: 'powerConsumption',
        label: '주요 사양',
        placeholder: '(카메라와 캠코더의 경우 촬영 화소 수, 영상 촬영 간격 등)',
        type: 'textarea',
        required: false,
      },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  smallElectronic: {
    ...PRODUCT_INFO_DISC_CATEGORY['smallElectronic'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: false },
      {
        key: 'kc',
        label: 'KC 인증정보',
        placeholder:
          '([전기용품 및 생활용품 안전관리법]에 따른 안전인증·안전확인·공급자적합성확인대상제품 및 [전파법]에 따른 적합인증·적합등록 대상 기자재에 한함)',
        type: 'textarea',
        required: false,
      },
      { key: 'powerConsumption', label: '정격전압, 소비전력', required: false },
      { key: 'manufacturingDate', label: '동일모델의 출시년월', required: false },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'size', label: '크기, 무게', required: false },
      { key: 'powerConsumption', label: '주요 사양', type: 'textarea', required: false },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  mobileCommunication: {
    ...PRODUCT_INFO_DISC_CATEGORY['mobileCommunication'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: false },
      {
        key: 'kc',
        label: 'KC 인증정보',
        placeholder:
          '([전기용품 및 생활용품 안전관리법]에 따른 안전인증·안전확인·공급자적합성확인대상제품 및 [전파법]에 따른 적합인증·적합등록 대상 기자재에 한함)',
        type: 'textarea',
        required: false,
      },
      { key: 'manufacturingDate', label: '동일모델의 출시년월', required: false },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'size', label: '크기, 무게', required: false },
      { key: 'mobileRequirements', label: '이동통신 가입조건', type: 'textarea', required: false },
      { key: 'mobileCarrier', label: '이동통신사', required: false },
      { key: 'registrationProcess', label: '가입절차', type: 'textarea', required: false },
      {
        key: 'consumerBurden',
        label: '소비자의 추가적인 부담사항',
        placeholder: '(가입비, 유심카드 구입비 등 추가로 부담하여야 할 금액, 부가서비스, 의무사용기간, 위약금 등)',
        type: 'textarea',
        required: false,
      },
      { key: 'powerConsumption', label: '주요 사양', type: 'textarea', required: false },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  navigation: {
    ...PRODUCT_INFO_DISC_CATEGORY['navigation'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: false },
      {
        key: 'kc',
        label: 'KC 인증정보',
        placeholder: '([전파법]에 따른 적합인증·적합등록 대상 기자재에 한함)',
        type: 'textarea',
        required: false,
      },
      { key: 'powerConsumption', label: '정격전압, 소비전력', required: false },
      { key: 'manufacturingDate', label: '동일모델의 출시년월', required: false },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'size', label: '크기, 무게', required: false },
      { key: 'powerConsumption', label: '주요 사양', type: 'textarea', required: false },
      { key: 'mapUpdateCost', label: '맵 업데이트 비용 및 무상기간', required: false },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  automotive: {
    ...PRODUCT_INFO_DISC_CATEGORY['automotive'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: false },
      { key: 'manufacturingDate', label: '동일모델의 출시년월', required: false },
      {
        key: 'kc',
        label: 'KC 인증정보',
        placeholder:
          '([자동차관리법]에 따른 부품자기인증 대상 자동차부품, [전기용품 및 생활용품 안전관리법]에 따른 안전인증·안전확인·공급자적합성확인대상제품 및 [전파법]에 따른 적합인증·적합등록 대상 기자재에 한함)',
        type: 'textarea',
        required: false,
      },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'size', label: '크기', required: false },
      { key: 'application', label: '적용차종', required: false },
      {
        key: 'risk',
        label: '제품사용으로 인한 위험 및 유의사항',
        placeholder: '(연료절감장치에 한함)',
        type: 'textarea',
        required: false,
      },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
      {
        key: 'testCertificate',
        label: '검사합격증 번호',
        placeholder: '([대기환경보전법]에 따른 첨가제·촉매제에 한함)',
        required: false,
      },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  medicalEquipment: {
    ...PRODUCT_INFO_DISC_CATEGORY['medicalEquipment'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: false },
      {
        key: 'License',
        label: '허가·인증·신고번호',
        placeholder: '([의료기기법]에 따른 허가·인증·신고 대상 의료기기에 한함)',
        required: true,
      },
      { key: 'powerConsumption', label: '정격전압, 소비전력 (전기용품에 한함)', required: false },
      { key: 'manufacturingDate', label: '동일모델의 출시년월', required: false },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      { key: 'usage', label: '제품의 사용목적 및 사용방법', type: 'textarea', required: false },
      { key: 'precautions', label: '취급시 주의사항', type: 'textarea', required: false },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  kitchen: {
    ...PRODUCT_INFO_DISC_CATEGORY['kitchen'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: false },
      { key: 'material', label: '재질', required: false },
      { key: 'parts', label: '구성품', required: false },
      { key: 'size', label: '크기', required: false },
      { key: 'manufacturingDate', label: '동일모델의 출시년월', required: false },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      {
        key: 'packaging ',
        label: '수입기구 또는 용기·포장',
        placeholder: '수입기구 또는 용기·포장의 경우 “수입식품안전관리특별법에 따른 수입신고를 필함”의 문구',
        required: false,
      },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  cosmetics: {
    ...PRODUCT_INFO_DISC_CATEGORY['cosmetics'],
    fields: [
      { key: 'volume', label: '내용물의 용량 또는 중량', required: false },
      { key: 'specs', label: '제품 주요 사양 (피부타입, 색상(호, 번) 등)', type: 'textarea', required: true },
      {
        key: 'expiryDate',
        label: '사용기한 또는 개봉 후 사용기간',
        placeholder: '(개봉 후 사용기간을 기재할 경우에는 제조연월일을 병행표기)',
        required: true,
      },
      { key: 'directions', label: '사용방법', required: true },
      {
        key: 'manufacturer',
        label: '화장품제조업자, 화장품책임판매업자 및 맞춤형화장품판매업자',
        required: true,
      },
      { key: 'origin', label: '제조국/원산지', required: true },
      {
        key: 'ingredients',
        label: '[화장품법]에 따라 기재·표시하여야 하는 모든 성분',
        type: 'textarea',
        required: false,
      },
      {
        key: 'cosmeceuticals',
        label: '기능성 화장품',
        placeholder:
          '기능성 화장품(미백, 주름개선, 자외선 차단제품 등)의 경우 “화장품법에 따른 기능성 화장품 심사(또는 보고)를 필함”의 문구',
        required: true,
      },
      { key: 'precautions', label: '사용시 주의사항', type: 'textarea', required: true },
      { key: 'qualityAssurance', label: '품질보증기준', required: false },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  jewelry: {
    ...PRODUCT_INFO_DISC_CATEGORY['jewelry'],
    fields: [
      { key: 'material', label: '소재 / 순도 / 밴드재질 (시계의 경우)', type: 'textarea', required: true },
      { key: 'weight', label: '중량', required: true },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국', placeholder: '(원산지와 가공지 등이 다를 경우 함께 표기)', required: true },
      { key: 'size', label: '치수', required: true },
      { key: 'precautions', label: '착용 시 주의사항', type: 'textarea', required: true },
      { key: 'spec', label: '주요 사양', type: 'textarea', required: true },
      { key: 'tier', label: '귀금속, 보석류 - 등급', required: true },
      { key: 'skill', label: '시계 - 기능, 방수 등', required: true },
      { key: 'isWarranty', label: '보증서 제공여부', required: true },
      { key: 'qualityAssurance', label: '품질보증기준', required: true },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  agricultural: {
    ...PRODUCT_INFO_DISC_CATEGORY['agricultural'],
    fields: [
      { key: 'modelName', label: '품목 또는 명칭', required: true },
      { key: 'size', label: '포장단위별 내용물의 용량(중량),수량,크기', type: 'textarea', required: true },
      { key: 'manufacturer', label: '생산자,수입품의 경우 수입자를 함께 표기', required: true },
      { key: 'origin', label: '[농수산물의 원산지 표시 등에 관한 법률]에 따른 원산지', required: true },
      { key: 'manufacturingDate', label: '제조연월일, 소비기한 또는 품질유지기한', required: true },
      { key: 'labeling', label: '세부 품목군별 표시사항', type: 'textarea', required: true },
      {
        key: 'agriculturalAndMarineProducts',
        label: '유전자변형농수산물, 지리적 표시',
        placeholder: '[농수산물 품질관리법]에 따른 유전자변형농수산물 표시, 지리적 표시',
        required: true,
      },
      {
        key: 'livestockIndustry',
        label: '[축산법]에 따른 등급 표시',
        placeholder:
          '(1++ 등급 국내산 쇠고기의 경우 [소·돼지 식육의 표시방법 및 부위 구분기준]에 따라 근내지방도 정보를 포함하여 표시), [가축 및 축산물 이력관리에 관한 법률]에 따른 이력관리대상축산물 유무',
        required: true,
      },
      {
        key: 'importAgriculturalAndMarineProducts',
        label: '수입 농수축산물',
        placeholder: '“수입식품안전관리 특별법에 따른 수입신고를 필함”의 문구',
        required: true,
      },
      { key: 'parts', label: '상품구성', required: true },
      { key: 'storage', label: '보관방법 또는 취급방법', required: true },
      {
        key: 'precautions',
        label: '소비자 안전을 위한 주의사항',
        placeholder: '([식품 등의 표시·광고에 관한 법률 시행규칙] 제5조 및 [별표 2]에 따른 표시사항을 말함)',
        type: 'textarea',
        required: true,
      },
      { key: 'asCenter', label: '소비자 상담 관련 전화번호', required: true },
    ],
  },
  processedFood: {
    ...PRODUCT_INFO_DISC_CATEGORY['processedFood'],
    fields: [
      {
        key: 'labeling',
        label: '표시사항',
        placeholder: '[식품 등의 표시·광고에 관한 법률] 및 [식품등의 표시기준]에 따른 표시사항',
        type: 'textarea',
        required: true,
      },
      { key: 'productName', label: '제품명', required: true },
      { key: 'foodType', label: '식품의 유형', required: true },
      {
        key: 'manufacturer',
        label: '생산자 및 소재지',
        placeholder: '(수입품의 경우 생산자,수입자 및 제조국)',
        required: true,
      },
      { key: 'manufacturingDate', label: '제조연월일, 소비기한 또는 품질유지기한', required: true },
      { key: 'weight', label: '포장단위별 내용물의 용량(중량),수량', required: true },
      {
        key: 'rawMaterial',
        label: '원재료명',
        placeholder:
          '([농수산물의 원산지 표시 등에 관한 법률]에 따른 원산지 표시 포함) 및 함량(원재료 함량 표시대상 식품에 한함)',
        type: 'textarea',
        required: true,
      },
      { key: 'nutrient', label: '영양성분 (영양성분 표시대상 식품에 한함)', type: 'textarea', required: true },
      { key: 'gmo', label: '유전자변형식품에 해당하는 경우의 표시', required: true },
      {
        key: 'precautions',
        label: '소비자 안전을 위한 주의사항',
        placeholder: '([식품 등의 표시·광고에 관한 법률 시행규칙] 제5조 및 [별표 2]에 따른 표시사항을 말함)',
        type: 'textarea',
        required: true,
      },
      {
        key: 'importedFood',
        label: '수입식품',
        placeholder: '수입식품의 경우 “수입식품안전관리 특별법에 따른 수입신고를 필함”의 문구',
        required: true,
      },
      { key: 'asCenter', label: '소비자 상담 관련 전화번호', required: true },
    ],
  },
  healthFood: {
    ...PRODUCT_INFO_DISC_CATEGORY['healthFood'],
    fields: [
      {
        key: 'labeling',
        label: '표시사항',
        placeholder: '[식품 등의 표시·광고에 관한 법률] 및 [건강기능식품의 표시기준]에 따른',
        type: 'textarea',
        required: true,
      },
      { key: 'productName', label: '제품명', required: true },
      {
        key: 'manufacturer',
        label: '제조업소의 명칭과 소재지',
        placeholder: '(수입품의 경우 수입업소명, 제조업소명 및 수출국명)',
        required: true,
      },
      { key: 'storage', label: '소비기한 및 보관방법', required: true },
      { key: 'weight', label: '포장단위별 내용물의 용량(중량), 수량', required: true },
      {
        key: 'rawMaterial',
        label: '원료명 및 함량',
        placeholder: '([농수산물의 원산지 표시 등에 관한 법률]에 따른 원산지 표시 포함)',
        type: 'textarea',
        required: true,
      },
      { key: 'nutrient', label: '영양정보', type: 'textarea', required: true },
      { key: 'nutritionalFacts:', label: '기능정보', type: 'textarea', required: true },
      {
        key: 'intake',
        label: '섭취량,섭취방법',
        placeholder: '섭취량,섭취방법 및 섭취 시 주의사항 및 부작용 가능성',
        type: 'textarea',
        required: true,
      },
      {
        key: 'notPreventionContent',
        label: '표현',
        placeholder: '질병의 예방 및 치료를 위한 의약품이 아니라는 내용의 표현',
        required: true,
      },
      {
        key: 'precautions',
        label: '소비자 안전을 위한 주의사항',
        placeholder: '([식품 등의 표시·광고에 관한 법률 시행규칙] 제5조 및 [별표 2]에 따른 표시사항을 말함)',
        type: 'textarea',
        required: true,
      },
      {
        key: 'gmo',
        label: '유전자변형건강기능식품 표시',
        placeholder: '[건강기능식품에 관한 법률]에 따른 유전자변형건강기능식품 표시 (해당 경우에 한함)',
        required: true,
      },
      {
        key: 'importedHealthFunctionalFood',
        label: '수입 건강기능식품',
        placeholder: '수입 건강기능식품의 경우 “수입식품안전관리특별법에 따른 수입신고를 필함”의 문구',
        required: true,
      },
      { key: 'asCenter', label: '소비자 상담 관련 전화번호', required: true },
    ],
  },
  children: {
    ...PRODUCT_INFO_DISC_CATEGORY['children'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: true },
      {
        key: 'kc',
        label: 'KC 인증정보',
        placeholder: '([어린이제품 안전 특별법]에 따른 안전인증·안전확인·공급자적합성확인대상어린이제품에 한함)',
        type: 'textarea',
        required: true,
      },
      { key: 'size', label: '크기, 중량', placeholder: '(섬유제품 등의 경우 치수 정보로 대체 가능)', required: true },
      { key: 'color', label: '색상', required: true },
      { key: 'material', label: '재질', placeholder: '(섬유의 경우 혼용률)', required: true },
      { key: 'recommendedAge', label: '사용연령 또는 권장사용연령', required: true },
      {
        key: 'limit',
        label: '크기·체중의 한계',
        placeholder: '(착용 또는 탑승용 어린이제품과 같이 크기·체중에 제한이 있는 품목의 경우 반드시 표시)',
        required: true,
      },
      { key: 'manufacturingDate', label: '동일모델의 출시년월', required: true },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국', required: true },
      {
        key: 'precautions',
        label: '취급방법 및 주의사항',
        placeholder: '취급방법 및 취급시 주의사항, 안전표시 (주의, 경고 등)',
        type: 'textarea',
        required: true,
      },
      { key: 'qualityAssurance', label: '품질보증기준', required: true },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  musicalInstrument: {
    ...PRODUCT_INFO_DISC_CATEGORY['musicalInstrument'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: true },
      { key: 'size', label: '크기', required: true },
      { key: 'color', label: '색상', required: true },
      { key: 'material', label: '재질', required: true },
      { key: 'parts', label: '제품 구성', type: 'textarea', required: true },
      { key: 'manufacturingDate', label: '동일모델의 출시년월', required: true },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국', required: true },
      { key: 'powerConsumption', label: '상품별 세부 사양', required: true },
      { key: 'qualityAssurance', label: '품질보증기준', required: true },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  sports: {
    ...PRODUCT_INFO_DISC_CATEGORY['sports'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: true },
      {
        key: 'kc',
        label: 'KC 인증정보',
        placeholder: '([전기용품 및 생활용품 안전관리법]에 따른 안전인증·안전확인·공급자적합성확인대상제품에 한함)',
        type: 'textarea',
        required: true,
      },
      { key: 'size', label: '크기, 중량', required: true },
      { key: 'color', label: '색상', required: true },
      { key: 'material', label: '재질', required: true },
      { key: 'parts', label: '제품 구성', type: 'textarea', required: true },
      { key: 'manufacturingDate', label: '동일모델의 출시년월', required: true },
      {
        key: 'manufacturer',
        label: '제조자, 수입품의 경우 수입자를 함께 표기',
        placeholder: '(병행수입의 경우 병행수입 여부로 대체 가능)',
        required: true,
      },
      { key: 'origin', label: '제조국', required: true },
      { key: 'powerConsumption', label: '상품별 세부 사양', type: 'textarea', required: true },
      { key: 'qualityAssurance', label: '품질보증기준', required: true },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호', required: true },
    ],
  },
  books: {
    ...PRODUCT_INFO_DISC_CATEGORY['books'],
    fields: [
      { key: 'bookName', label: '도서명', required: true },
      { key: 'authorAndPublisher', label: '저자, 출판사', required: true },
      { key: 'size', label: '크기', placeholder: '(전자책의 경우 파일의 용량)', required: true },
      { key: 'pages', label: '쪽수', placeholder: '(전자책의 경우 제외)', required: true },
      { key: 'parts', label: '제품 구성', placeholder: '(전집 또는 세트일 경우 낱권 구성, CD 등)', required: true },
      {
        key: 'publishDate',
        label: '발행일',
        placeholder:
          '([출판문화산업 진흥법] 제2조 및 제22조의 규정에 따른 것으로, 매 판을 처음 인쇄한 날을 말함. 단, 매 판을 구분할 때에 오탈자의 변경 등 경미한 변경에 따라 다시 인쇄하는 경우는 제외)',
        required: true,
      },
      {
        key: 'contents',
        label: '목차 또는 책소개',
        placeholder: '(아동용 학습교재의 경우 사용연령을 포함)',
        required: true,
      },
    ],
  },
  hotel: {
    ...PRODUCT_INFO_DISC_CATEGORY['hotel'],
    fields: [
      { key: 'country', label: '국가 또는 지역명', required: true },
      { key: 'lodgingType', label: '숙소 형태', required: true },
      { key: 'roomType', label: '등급, 객실 타입', required: true },
      { key: 'personnel', label: '사용가능 인원, 인원 추가 시 비용', required: true },
      { key: 'service', label: '부대시설, 제공 서비스', placeholder: '(조식 등)', required: true },
      { key: 'cancellationPolicy', label: '취소 규정', placeholder: '(환불, 위약금 등)', required: true },
      { key: 'reservationContact', label: '예약 담당 연락처', required: true },
    ],
  },
  travelPackage: {
    ...PRODUCT_INFO_DISC_CATEGORY['travelPackage'],
    fields: [
      { key: 'travelAgency', label: '여행사', required: true },
      { key: 'flight', label: '이용항공편', required: true },
      { key: 'period', label: '여행기간 및 일정', required: true },
      { key: 'personnel', label: '총 예정 인원, 출발 가능 인원', required: true },
      { key: 'accommodationInfo', label: '숙박정보', type: 'textarea', required: true },
      {
        key: 'travelPrice',
        label: '여행상품 가격',
        placeholder:
          '(유류할증료, 공항이용료, 전쟁보험료, 관광진흥개발기금, 운송요금, 숙박요금, 식사요금, 가이드 경비, 여행자보험료, 현지관광입장료 등 소비자가 특정 여행상품을 선택할 경우 부담해야 하는 모든 경비가 포함되어야 함. 다만, 가이드 경비를 현지에서 지불하여야하는 경우 별도로 그 금액을 표시할 수 있으며, 현지에서 별도로 지불해야 한다는 점을 표시하여야 함)',
        required: true,
      },
      { key: 'expensesAnddetail', label: '선택경비 유무 및 세부 내용', type: 'textarea', required: true },
      {
        key: 'isTravelExpenses',
        label: '선택경비 유무 등',
        placeholder:
          '(선택관광 경비 등 현지에서 개별 구매자의 필요나 선택에 의하여 지출하게 되는 경비가 있는지 여부 및 소비자의 선택에 따라 자유롭게 지불할 수 있다는 점을 함께 표시하여야 함)',
        required: true,
      },
      {
        key: 'optionalTour',
        label: '선택관광 및 대체일정',
        placeholder: '(선택관광 경비의 금액 및 선택관광을 선택하지 않을 경우의 대체 일정을 함께 표시하여야 함)',
        required: true,
      },
      {
        key: 'guideTip',
        label: '가이드 팁',
        placeholder:
          '(가이드 팁에 대하여 기재할 경우에는 가이드 경비와 구별하여 자유롭게 지불여부를 결정할 수 있음을 표시하여야 함. 다만, 정액으로 지불을 권장하는 등 소비자가 필수적으로 지불하여야 하는 경비인 것처럼 오인하지 않도록 표시하여야 함)',
        required: true,
      },
      { key: 'cancellationPolicy', label: '취소 규정 (환불, 위약금 등)', type: 'textarea', required: true },
      {
        key: 'travelWarningLevel',
        label: '여행경보단계',
        placeholder: '해외여행의 경우 외교통상부가 지정하는 여행경보단계',
        required: true,
      },
      { key: 'reservationContact', label: '예약 담당 연락처', required: true },
    ],
  },
  airlineTicket: {
    ...PRODUCT_INFO_DISC_CATEGORY['airlineTicket'],
    fields: [
      { key: 'isRoundTrip', label: '요금조건, 왕복 · 편도 여부', required: true },
      { key: 'expiryDate', label: '유효기간', required: true },
      {
        key: 'restriction',
        label: '제한사항',
        type: 'textarea',
        placeholder: '(출발일, 귀국일 변경가능 여부 등)',
        required: true,
      },
      { key: 'ticket', label: '티켓수령방법', type: 'textarea', required: true },
      { key: 'seatType', label: '좌석종류', required: true },
      {
        key: 'otherAmounts',
        label: '가격에 포함되지 않은 내역 및 금액',
        placeholder: '(유류할증료, 공항이용료 등)',
        required: true,
      },
      {
        key: 'cancellationPolicy',
        label: '취소 규정',
        placeholder: '(환불, 위약금 등)',
        type: 'textarea',
        required: true,
      },
      { key: 'reservationContact', label: '예약 담당 연락처', required: true },
    ],
  },
  rentalCar: {
    ...PRODUCT_INFO_DISC_CATEGORY['rentalCar'],
    fields: [
      { key: 'catType', label: '차종', required: true },
      {
        key: 'ownership',
        label: '소유권 이전 조건',
        placeholder: '(소유권이 이전되는 경우에 한함)',
        type: 'textarea',
        required: true,
      },
      { key: 'otherAmounts', label: '추가 선택 시 비용', placeholder: '(자차면책제도, 내비게이션 등)', required: true },
      { key: 'settlement', label: '차량 반환 시 연료대금 정산 방법', type: 'textarea', required: true },
      { key: 'consumerResponsibility', label: '차량의 고장·훼손 시 소비자 책임', type: 'textarea', required: true },
      { key: 'cancellationPolicy', label: '예약 취소 또는 중도 해약 시 환불 기준', type: 'textarea', required: true },
      { key: 'asCenter', label: '소비자 상담 관련 전화번호', required: true },
    ],
  },
  rentalProduct: {
    ...PRODUCT_INFO_DISC_CATEGORY['rentalProduct'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: true },
      {
        key: 'ownership',
        label: '소유권 이전 조건',
        placeholder:
          '(소유권이 이전되는 경우에 한하여, 소유권 이전에 필요한 렌탈기간 또는 총 렌탈금액 등 요건을 구체적으로 명시)',
        type: 'textarea',
        required: true,
      },
      {
        key: 'maintenance',
        label: '유지보수 조건',
        placeholder: '(점검·필터교환 주기, 추가 비용 등)',
        type: 'textarea',
        required: true,
      },
      {
        key: 'consumerResponsibility',
        label: '상품의 고장·분실·훼손 시 소비자 책임',
        type: 'textarea',
        required: true,
      },
      { key: 'cancellationPolicy', label: '중도 해약 시 환불 기준', type: 'textarea', required: true },
      { key: 'spec', label: '제품 사양', placeholder: '(용량, 소비전력 등)', type: 'textarea', required: true },
      { key: 'asCenter', label: '소비자 상담 관련 전화번호', required: true },
    ],
  },
  rentalBook: {
    ...PRODUCT_INFO_DISC_CATEGORY['rentalBook'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: true },
      {
        key: 'ownership',
        label: '소유권 이전 조건',
        placeholder:
          '(소유권이 이전되는 경우에 한하여, 소유권 이전에 필요한 렌탈기간 또는 총 렌탈금액 등 요건을 구체적으로 명시)',
        type: 'textarea',
        required: true,
      },
      { key: 'consumerResponsibility', label: '상품의 고장·분실·훼손 시 소비자 책임', required: true },
      { key: 'cancellationPolicy', label: '중도 해약 시 환불 기준', type: 'textarea', required: true },
      { key: 'asCenter', label: '소비자 상담 관련 전화번호', required: true },
    ],
  },
  digitalContent: {
    ...PRODUCT_INFO_DISC_CATEGORY['digitalContent'],
    fields: [
      { key: 'producer', label: '제작자 또는 공급자', required: true },
      { key: 'termsOfUse', label: '이용조건, 이용기간', required: true },
      { key: 'provide', label: '상품 제공 방식', placeholder: '(CD, 다운로드, 실시간 스트리밍 등)', required: true },
      { key: 'spec', label: '최소 시스템 사양, 필수 소프트웨어', type: 'textarea', required: true },
      {
        key: 'Revocation',
        label: '청약철회',
        placeholder: '청약철회 또는 계약의 해제 · 해지에 따른 효과',
        type: 'textarea',
        required: true,
      },
      { key: 'asCenter', label: '소비자 상담 관련 전화번호', required: true },
    ],
  },
  giftCard: {
    ...PRODUCT_INFO_DISC_CATEGORY['giftCard'],
    fields: [
      { key: 'issuer', label: '발행자', required: true },
      {
        key: 'termsOfUse',
        label: '유효기간, 이용조건',
        placeholder: '(유효기간 경과 시 보상 기준, 사용제한품목 및 기간 등)',
        required: true,
      },
      { key: 'availableShop', label: '이용 가능 매장', required: true },
      { key: 'refund', label: '잔액 환급 조건', type: 'textarea', required: true },
      { key: 'asCenter', label: '소비자 상담 관련 전화번호', required: true },
    ],
  },
  mobileCoupon: {
    ...PRODUCT_INFO_DISC_CATEGORY['mobileCoupon'],
    fields: [
      { key: 'issuer', label: '발행자', required: true },
      {
        key: 'termsOfUse',
        label: '유효기간, 이용조건',
        placeholder: '(유효기간 경과 시 보상 기준, 사용제한품목 및 기간 등)',
        required: true,
      },
      { key: 'availableShop', label: '이용 가능 매장', required: true },
      { key: 'refund', label: '환불조건 및 방법', type: 'textarea', required: true },
      { key: 'asCenter', label: '소비자 상담 관련 전화번호', required: true },
    ],
  },
  moviePerformance: {
    ...PRODUCT_INFO_DISC_CATEGORY['moviePerformance'],
    fields: [
      { key: 'host', label: '주최 또는 기획', placeholder: '(공연에 한함)', required: true },
      { key: 'leadRole', label: '주연', placeholder: '(공연에 한함)', required: true },
      { key: 'rating', label: '관람등급', required: true },
      { key: 'runningTime', label: '상영·공연시간', required: true },
      { key: 'theater', label: '상영·공연장소', required: true },
      { key: 'reservation', label: '예매 취소 조건', type: 'textarea', required: true },
      { key: 'refund', label: '취소·환불방법', required: true },
      { key: 'asCenter', label: '소비자 상담 관련 전화번호', required: true },
    ],
  },
  chemicalProduct: {
    ...PRODUCT_INFO_DISC_CATEGORY['chemicalProduct'],
    fields: [
      {
        key: 'labeling',
        label: '표시사항',
        placeholder: '화학제품안전법 및 [안전확인대상생활화학제품 지정 및 안전·표시기준]에 따른 표시사항',
        type: 'textarea',
        required: true,
      },
      { key: 'productName', label: '품목 및 제품명', required: true },
      { key: 'use', label: '용도 및 제형', placeholder: '(표백제의 경우 계열을 함께 표시)', required: true },
      {
        key: 'manufacturingDate',
        label: '제조연월 및 유통기한',
        placeholder: '(유통기한의 경우 해당 없는 제품은 생략 가능)',
        required: true,
      },
      { key: 'size', label: '중량·용량·매수·크기', required: true },
      { key: 'effect', label: '효과·효능', placeholder: '(승인대상 제품에 한함)', type: 'textarea', required: true },
      { key: 'importer', label: '수입자(수입제품에 한함),제조국 및 제조사', required: true },
      { key: 'CRP', label: '어린이 보호포장 대상 제품 유무', required: true },
      {
        key: 'chemicalName',
        label: '제품에 사용된 화학물질 명칭',
        placeholder:
          '([안전확인대상생활화학제품 지정 및 안전·표시기준] [별표 6]에 따른 표시대상 화학물질로서 주요물질, 보존제, 알레르기반응가능물질 등의 명칭)',
        type: 'textarea',
        required: true,
      },
      { key: 'precautions', label: '사용상 주의사항', type: 'textarea', required: true },
      {
        key: 'reportNumber',
        label: '안전기준적합확인신고번호 또는 안전확인대상생활화학제품승인번호',
        placeholder:
          '(화학제품안전법 시행일(경과조치 기간 포함) 이전에 생산·수입된 위해우려제품의 경우 종전 법에 따른 자가검사번호를 표시)',
        required: true,
      },
      { key: 'asCenter', label: '소비자 상담 관련 전화번호', required: true },
    ],
  },
  biologicalProduct: {
    ...PRODUCT_INFO_DISC_CATEGORY['biologicalProduct'],
    fields: [
      {
        key: 'labeling',
        label: '표시사항',
        placeholder:
          '[생활화학제품 및 살생물제의 안전관리에 관한 법률] 및 [살생물제품 표시에 관한 규정]에 따른 표시사항',
        type: 'textarea',
        required: true,
      },
      { key: 'productName', label: '제품명 및 살생물제품유형', required: true },
      { key: 'expirationDate', label: '유통기한', required: true },
      { key: 'weight', label: '중량 또는 용량 및 표준사용량', required: true },
      { key: 'effect', label: '효과·효능', type: 'textarea', required: true },
      { key: 'userAndRange', label: '사용대상자 및 사용범위', required: true },
      { key: 'importer', label: '수입자(수입제품에 한함), 제조국 및 제조사', required: true },
      { key: 'CRP', label: '어린이보호포장 대상제품 유무', required: true },
      {
        key: 'chemicalName',
        label: '화학물질 명칭',
        placeholder: '살생물물질, 나노물질, 기타 화학물질(유해화학물질 또는 중점관리물질)의 명칭',
        type: 'textarea',
        required: true,
      },
      { key: 'hazard', label: '제품 유해성·위해성 표시', required: true },
      { key: 'precautions', label: '사용방법 및 사용상 주의사항', type: 'textarea', required: true },
      { key: 'reportNumber', label: '승인번호', required: true },
      { key: 'asCenter', label: '소비자 상담 관련 전화번호', required: true },
    ],
  },
  service: {
    ...PRODUCT_INFO_DISC_CATEGORY['service'],
    fields: [
      { key: 'businessOwner', label: '서비스 제공 사업자', required: true },
      {
        key: 'license',
        label: '법에 의한 인증·허가 등을 받았음을 확인할 수 있는 경우 그에 대한 사항',
        required: true,
      },
      { key: 'termsOfUse', label: '이용조건', placeholder: '(이용가능 기간·장소, 추가비용 등)', required: true },
      { key: 'refundPolicy', label: '취소·중도해약·해지 조건 및 환불기준', type: 'textarea', required: true },
      { key: 'refund', label: '취소·환불방법', type: 'textarea', required: true },
      { key: 'asCenter', label: '소비자 상담 관련 전화번호', required: true },
    ],
  },
  others: {
    ...PRODUCT_INFO_DISC_CATEGORY['others'],
    fields: [
      { key: 'modelName', label: '품명 및 모델명', required: true },
      {
        key: 'license',
        label: '법에 의한 인증·허가 등을 받았음을 확인할 수 있는 경우 그에 대한 사항',
        required: true,
      },
      { key: 'origin', label: '제조국 또는 원산지', required: true },
      { key: 'manufacturer', label: '제조자, 수입품의 경우 수입자를 함께 표기', required: true },
      { key: 'asCenter', label: 'A/S 책임자와 전화번호 또는 소비자 상담 관련 전화번호', required: true },
    ],
  },
};
